project:
  type: website
  output-dir: docs

website:
  title: "Pyro"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home

      - href: pages/data-explained.qmd
        text: Data Explained

      - href: pages/data-projects.qmd
        text: Data Projects

      - href: pages/chess.qmd
        text: Chess

      - href: blog.qmd
        text: Blog

format:
  html:
    theme: darkly
    css: styles.css
    toc: false



